(* ::Package:: *)

(* ::Input:: *)
(*(*Author:Midhun Varghese*)
(*GitHub:https://github.com/midhun-varghese*)
(**)
(*This program is used to develop the forward kinematics of any serial manipulator from its DH Parameters.The associated transformation matrix and the Jacobian is also calculated.*)*)
(**)
(*(*Defining the DH Parameters for the PUMA 560 Robot*)*)
(**)
(*DOF = 6 ;*)
(**)
(*\[Alpha][0]=0;              a[0]=0;         d[1]=0;         \[Theta][1]=\[Theta][1];     jtype[1]=1;*)
(*\[Alpha][1]=-Pi/2;   a[1]=0;         d[2]=0;         \[Theta][2]=\[Theta][2];     jtype[2]=1;*)
(*\[Alpha][2]=0;              a[2]=Subscript[a, 2];       d[3]=Subscript[d, 3];      \[Theta][3]=\[Theta][3];     jtype[3]=1;*)
(*\[Alpha][3]=-Pi/2;   a[3]=Subscript[a, 3];       d[4]=Subscript[d, 4];      \[Theta][4]=\[Theta][4];     jtype[4]=1;*)
(*\[Alpha][4]=Pi/2;      a[4]=0;         d[5]=0;        \[Theta][5]=\[Theta][5];     jtype[5]=1;*)
(*\[Alpha][5]=-Pi/2;   a[5]=0;         d[6]=0;        \[Theta][6]=\[Theta][6];     jtype[6]=1;*)
(**)
(*(*TOOL TIP POSITION IN LAST LINK FRAME*)*)
(**)
(*pNT={{0},{0},{Subscript[z, T]}};*)
(**)
(*Print[" DH Parameters"] ;*)
(*Print["Link i    \[Alpha][i-1]    a[i-1]      d[i]      \[Theta][i]      J-type[i]"] ;*)
(*Print["-------------------------------------------------------------"] ;*)
(*For [ i=1, i<=DOF, i++,*)
(*    Print["  ",i,"         ", \[Alpha][i-1],"        ", a[i-1],"         ",d[i],*)
(*      "       ", \[Theta][i],"         ",jtype[i]]*)
(*    ] ;*)
